trigger:
- main

pool:
  vmImage: windows-latest
  dotnet-version: '5.x'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/Plugins/SpecFlow.Actions.WindowsAppDriver/*.csproj'
- task: Windows Application Driver@0
  inputs:
    OperationType: 'Start'
    AgentResolution: '1080p'
# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'test'
#     projects: '**/Plugins/SpecFlow.Actions.WindowsAppDriver/*.csproj'
- task: Windows Application Driver@0
  inputs:
    OperationType: 'Stop'