name: SpecFlow.Actions.Android

on: 
  push:
    branches:
      - main
    paths:
      - '.github/workflows/specflow.actions.android.yaml'
      - 'Plugins/specflow.actions.android/**'
      - 'Plugins/*'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/specflow.actions.android.yaml'
      - 'Plugins/SpecFlow.Actions.Android/**'
      - 'Plugins/*'


jobs:
  build:
    runs-on: windows-latest
    env:
        DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Authenticates packages to push to GPR
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.0.3

      - name: Nuget Restore SpecFlow.Actions.Android.sln
        run: nuget restore Plugins/SpecFlow.Actions.Android/SpecFlow.Actions.Android.sln

      - name: MSBuild SpecFlow.Actions.Android.sln
        run: msbuild.exe Plugins/SpecFlow.Actions.Android/SpecFlow.Actions.Android.sln  
            
      - name: Create the package
        run: dotnet pack --no-restore --configuration Release Plugins\SpecFlow.Actions.Android\SpecFlow.Actions.Android.sln

      - name: Upload NuGet Package to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: NuGet-Package
          path:  |
            Plugins/SpecFlow.Actions.Android/SpecFlow.Actions.Android/bin/Release/**/*.nupkg
            Plugins/SpecFlow.Actions.Appium/SpecFlow.Actions.Appium/bin/Release/**/*.nupkg
            Plugins/SpecFlow.Actions.Configuration/SpecFlow.Actions.Configuration/bin/Release/**/*.nupkg
            
  release:
    runs-on: windows-latest
    env: 
      DOTNET_NOLOGO: true
    needs: build
    environment: NuGet.org
    if: github.ref == 'refs/heads/main'
    steps:
      # Authenticates packages to push to nuget.org.
      # It's only the way to push a package to nuget.org feed for macOS/Linux machines due to API key config store limitations.
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: NuGet-Package
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Publish the package to nuget.org
        shell: pwsh
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.SPECFLOW_ACTIONS_NUGET_TOKEN }}
        run: dotnet nuget push "**/*.nupkg" -k "$env:NUGET_AUTH_TOKEN" -s "https://api.nuget.org/v3/index.json" --skip-duplicate
