name: SpecFlow.Actions.WindowsAppDriver

trigger:
  - main

pool:
  vmImage: 'windows-latest'

workspace:
  clean: 'all'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Plugins/specflow.actions.WindowsAppDriver/*.csproj'
- task: Windows Application Driver@0
  inputs:
    OperationType: 'Start'
    AgentResolution: '1080p'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'Plugins/specflow.actions.WindowsAppDriver/*.csproj'

- task: Windows Application Driver@0
  inputs:
    OperationType: 'Stop'